version: '3'
services:
  db:
    image: mysql:latest
    container_name: go_db
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./sqls/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gorm_practice
      MYSQL_USER: user
      MYSQL_PASSWORD: password
volumes:
  mysql_data:
